# Run with "docker compose up", working prod environment

version: "3.8"

services:
  server:
    image: my-app-backend

  app:
    image: my-app-frontend

  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: my-app-reverse-proxy
    depends_on:
      - app
      - server
