# Run with docker compose -f docker-compose.dev.yml up

version: "3.8"

services:
  app:
    image: todo-frontend-dev
    # No need to support this
    # build:
    #   context: .
    #   dockerfile: todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    # ports:
    #   - 3001:3000
    container_name: todo-frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api

  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  mongo:
    image: mongo
    # ports:
    #   - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    # ports:
    #   - 6378:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend-dev
    # ports:
    #   - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
