# Get all
GET http://localhost:3000/todos

###

# Create new
POST http://localhost:3000/todos
Content-Type: application/json

{
  "text": "Test Redis",
  "done": "false"
}

###

# Get by id
GET http://localhost:3000/todos/659a890d7624d5fc8219f89e

###

# Modify by id
PUT http://localhost:3000/todos/659a890d7624d5fc8219f89e
Content-Type: application/json

{
  "done": true
}

###

# Delete
DELETE http://localhost:3000/todos/65a261761b5daa1773ca6cd9
